// <auto-generated />
using System;
using Eocr.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eocr.Server.Data.Migrations
{
    [DbContext(typeof(EocrDbContext))]
    [Migration("20261005190819_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eocr.Server.Data.Entities.Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodeType", "Value")
                        .IsUnique();

                    b.ToTable("Codes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeType = "UserRole",
                            IsActive = true,
                            IsSystem = true,
                            Label = "User",
                            SortOrder = 1,
                            Value = "User"
                        },
                        new
                        {
                            Id = 2,
                            CodeType = "UserRole",
                            IsActive = true,
                            IsSystem = true,
                            Label = "Admin",
                            SortOrder = 2,
                            Value = "Admin"
                        },
                        new
                        {
                            Id = 101,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "Draft",
                            SortOrder = 1,
                            Value = "Draft"
                        },
                        new
                        {
                            Id = 102,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "Submitted",
                            SortOrder = 2,
                            Value = "Submitted"
                        },
                        new
                        {
                            Id = 103,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "AI Review",
                            SortOrder = 3,
                            Value = "AiReview"
                        },
                        new
                        {
                            Id = 104,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "Human Review",
                            SortOrder = 4,
                            Value = "HumanReview"
                        },
                        new
                        {
                            Id = 105,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "More Info Needed",
                            SortOrder = 5,
                            Value = "MoreInfoNeeded"
                        },
                        new
                        {
                            Id = 106,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "Awaiting EEAAP",
                            SortOrder = 6,
                            Value = "AwaitingEeaap"
                        },
                        new
                        {
                            Id = 107,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "Approved",
                            SortOrder = 7,
                            Value = "Approved"
                        },
                        new
                        {
                            Id = 108,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "Approved with Conditions",
                            SortOrder = 8,
                            Value = "ApprovedWithConditions"
                        },
                        new
                        {
                            Id = 109,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "Denied",
                            SortOrder = 9,
                            Value = "Denied"
                        });
                });

            modelBuilder.Entity("Eocr.Server.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Eocr.Server.Data.Entities.VettingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RequestorId")
                        .HasColumnType("int");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RequestorId");

                    b.HasIndex("StatusId");

                    b.ToTable("VettingRequests");
                });

            modelBuilder.Entity("Eocr.Server.Data.Entities.User", b =>
                {
                    b.HasOne("Eocr.Server.Data.Entities.Code", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Eocr.Server.Data.Entities.VettingRequest", b =>
                {
                    b.HasOne("Eocr.Server.Data.Entities.User", "Requestor")
                        .WithMany("VettingRequests")
                        .HasForeignKey("RequestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eocr.Server.Data.Entities.Code", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Requestor");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Eocr.Server.Data.Entities.User", b =>
                {
                    b.Navigation("VettingRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
