// <auto-generated />
using System;
using Eocr.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eocr.Server.Data.Migrations
{
    [DbContext(typeof(EocrDbContext))]
    partial class EocrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eocr.Server.Data.Entities.Code", b =>
                {
                    b.Property<int>("CodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeId"));

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CodeId");

                    b.HasIndex("CodeType", "Value")
                        .IsUnique();

                    b.ToTable("Codes");

                    b.HasData(
                        new
                        {
                            CodeId = 1,
                            CodeType = "UserRole",
                            IsActive = true,
                            IsSystem = true,
                            Label = "User",
                            SortOrder = 1,
                            Value = "User"
                        },
                        new
                        {
                            CodeId = 2,
                            CodeType = "UserRole",
                            IsActive = true,
                            IsSystem = true,
                            Label = "Admin",
                            SortOrder = 2,
                            Value = "Admin"
                        },
                        new
                        {
                            CodeId = 101,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "Draft",
                            SortOrder = 1,
                            Value = "Draft"
                        },
                        new
                        {
                            CodeId = 102,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "Submitted",
                            SortOrder = 2,
                            Value = "Submitted"
                        },
                        new
                        {
                            CodeId = 103,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "AI Review",
                            SortOrder = 3,
                            Value = "AiReview"
                        },
                        new
                        {
                            CodeId = 104,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "Human Review",
                            SortOrder = 4,
                            Value = "HumanReview"
                        },
                        new
                        {
                            CodeId = 105,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "More Info Needed",
                            SortOrder = 5,
                            Value = "MoreInfoNeeded"
                        },
                        new
                        {
                            CodeId = 106,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "Awaiting EEAAP",
                            SortOrder = 6,
                            Value = "AwaitingEeaap"
                        },
                        new
                        {
                            CodeId = 107,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "Approved",
                            SortOrder = 7,
                            Value = "Approved"
                        },
                        new
                        {
                            CodeId = 108,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "Approved with Conditions",
                            SortOrder = 8,
                            Value = "ApprovedWithConditions"
                        },
                        new
                        {
                            CodeId = 109,
                            CodeType = "RequestStatus",
                            IsActive = true,
                            IsSystem = true,
                            Label = "Denied",
                            SortOrder = 9,
                            Value = "Denied"
                        });
                });

            modelBuilder.Entity("Eocr.Server.Data.Entities.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RequestorId")
                        .HasColumnType("int");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RequestId");

                    b.HasIndex("RequestorId");

                    b.HasIndex("StatusId");

                    b.ToTable("VettingRequests");
                });

            modelBuilder.Entity("Eocr.Server.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Eocr.Server.Data.Entities.Request", b =>
                {
                    b.HasOne("Eocr.Server.Data.Entities.User", "Requestor")
                        .WithMany("VettingRequests")
                        .HasForeignKey("RequestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eocr.Server.Data.Entities.Code", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Requestor");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Eocr.Server.Data.Entities.User", b =>
                {
                    b.HasOne("Eocr.Server.Data.Entities.Code", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Eocr.Server.Data.Entities.User", b =>
                {
                    b.Navigation("VettingRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
